# Welcome {-}

```{r "intro"}
#| echo: false
.gh_url <- file.path('https://github.com', rmarkdown::metadata[['github-repo']])
pkglines <- read.dcf("DESCRIPTION")
pkg <- pkglines[, "Package"][[1]]
version <- pkglines[, "Version"][[1]]
authors <- eval(parse(text = pkglines[, "Authors@R"]))
license <- pkglines[, "License"][[1]]
intro <- glue::glue(
    "**Package:** {pkg}<br/>\n", 
    "**Authors:** {paste(format(authors, include = c('given', 'family', 'role')), collapse = ', ')}<br/>\n", 
    "**Compiled:** {as.character(Sys.Date())}<br/>\n", 
    "**Package version:** {version}<br/>\n", 
    "**R version:** <b style='color:red;'>{R.version.string}</b><br/>\n", 
    "**BioC version:** <b style='color:red;'>{BiocManager::version()}</b><br/>\n", 
    "**License:** {license}<br/>"
)
```

`r intro`

This `BiocBook` is used to demonstrate the OHCA package at the Bioconductor Conference 2023. 

::: {.callout-tip icon='true'}
## 📚 The OHCA book is the main documentation, and is available [here](https://jserizay.com/OHCA/). {.unnumbered .unlisted}
:::

## Description

This demonstration focuses on the `OHCA` ecosystem, including the 
following packages : 

- `HiCool`
- `HiCExperiment`
- `HiContacts`
- `fourDNData`

## Pre-requisites

* Familiarity with the `tidyverse` syntax; 
* Familiarity with the `GenomicRanges` class; 
* Basic understanding of Hi-C principles

For more information on Hi-C experimental approach and principles, 
read [OHCA book first chapter](https://jserizay.com/OHCA/principles.html).

## Time outline

| Activity                     | Time |
|------------------------------|------|
| Introduction to Hi-C         | 10m  |
| OHCA ecosystem               | 10m  |
| Demonstration with real data | 20m  |
| Wrapping up                  | 5m   |

## Docker image

To quickly use the `BiocBook` Docker image:

```sh
docker run -it -e PASSWORD=OHCA -p 8787:8787 ghcr.io/js2264/BiocBook.OHCA.Bioc2023:RELEASE_3_17
```

Once running, navigate to http://localhost:8787/ and then login 
with `rstudio`:`OHCA`. 
